permalink: /p/:title/
author: faisal
email: mfhsn@protonmail.com
title: nshfm
description: serially experimenting.
git_usr: faisalhsn
git_repo: https://github.com/faisalhsn/
insta: https://instagram.com/mfhsn01
logo: "/assets/img/logo.png"
